/* eslint-disable arrow-body-style */
const webpack                         = require('webpack');
const HtmlWebpackPlugin               = require('html-webpack-plugin');
const { withCommonConfig, CONSTANTS } = require('./webpack.common');

module.exports = withCommonConfig({
    // Emit a source map for easier debugging
    // See https://webpack.js.org/configuration/devtool/#devtool
    devtool: 'eval-source-map',

    entry: [
        require.resolve('react-app-polyfill/ie11'),
        'webpack-hot-middleware/client?reload=true',
        `${ CONSTANTS.PATHS.SRC }/index.js`,
    ],

    // Don't use hashes in dev mode for better performance
    output: {
        filename:      '[name].js',
        chunkFilename: '[name].chunk.js',
    },

    optimization: {
        splitChunks: {
            chunks: 'all',
        },
    },

    // Add development plugins
    plugins: [
        new webpack.HotModuleReplacementPlugin(), // Tell webpack we want hot reloading
        new HtmlWebpackPlugin({
            inject:   true, // Inject all files that are generated by webpack, e.g. bundle.js
            template: `${ CONSTANTS.PATHS.SRC }/index.html`,
        }),
    ],

    performance: {
        hints: false,
    },
});
